i = input().split(" ")
a = float(i[0])
b = float(i[1])
c = float(i[2])

print("TRIANGULO: %.3f" % ((a * c) / 2))
print("CIRCULO: %.3f" % (3.14159 * (c ** 2)))
print("TRAPEZIO: %.3f" % (((a + b) / 2) * c))
print("QUADRADO: %.3f" % (b ** 2))
print("RETANGULO: %.3f" % (a * b))
